apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: myapp
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 3000
      #nodePort: 30080
  selector:
    app: myapp