name: CI Pipeline (SAST, Docker Build, Trivy Scan, Push to Docker Hub)

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write  # ให้สิทธิ์อัปโหลดผลไปยัง GitHub Security Tab

jobs:
  sast_scan:
    name: SonarCloud SAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Run Linter (ESLint)
        run: npm run lint || true  # ให้รันต่อหากมี warning

      - name: Run SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonarqube-scanner \
            -Dsonar.projectKey=kalangun69300_test-my-app \
            -Dsonar.organization=kalangun69300 \
            -Dsonar.sources=src \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.token="${{ secrets.SONAR_TOKEN }}"

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: sast_scan  # ✅ รอให้ SonarCloud สแกนเสร็จก่อน

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:latest .
          echo "Built Docker Image: ${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:latest"

  security_scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    needs: build  # ✅ รอให้ Docker Image Build เสร็จก่อน

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy to Scan Docker Image
        uses: aquasecurity/trivy-action@0.15.0
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:latest'
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy Scan Results to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-image-results.sarif'

  push_image:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: security_scan  # ✅ รอให้ Trivy Scan เสร็จก่อนแล้วค่อย Push

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:latest
          echo "Pushed Docker Image: ${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:latest"
