name: CI Pipeline (SAST, Docker Build, Trivy Scan, Push to Docker Hub)

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write  # ให้สิทธิ์อัปโหลดผลไปยัง GitHub Security Tab

jobs:
  sast_scan:
    name: SonarCloud SAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Run Linter (ESLint)
        run: npm run lint || true  # ให้รันต่อหากมี warning

      - name: Run SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonarqube-scanner \
            -Dsonar.projectKey=kalangun69300_test-my-app \
            -Dsonar.organization=kalangun69300 \
            -Dsonar.sources=src \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.token="${{ secrets.SONAR_TOKEN }}"

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: sast_scan

    outputs:
      version: ${{ steps.version.outputs.VERSION }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Auto Version
        id: version
        run: |
          VERSION="v${{ github.run_number }}.0"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Next version: $VERSION"

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:latest .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:${{ env.VERSION }}
          docker save -o image-latest.tar ${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:latest
          docker save -o image-${{ env.VERSION }}.tar ${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:${{ env.VERSION }}

      - name: Upload Docker Image Artifact (latest)
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-latest
          path: image-latest.tar

      - name: Upload Docker Image Artifact (versioned)
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-versioned
          path: image-${{ env.VERSION }}.tar

  security_scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker Image Artifact (latest)
        uses: actions/download-artifact@v4
        with:
          name: docker-image-latest
          path: .

      - name: Download Docker Image Artifact (versioned)
        uses: actions/download-artifact@v4
        with:
          name: docker-image-versioned
          path: .

      - name: Load Docker Images
        run: |
          docker load -i image-latest.tar
          docker load -i image-${{ needs.build.outputs.version }}.tar

      - name: Run Trivy to Scan Docker Image (latest)
        uses: aquasecurity/trivy-action@0.15.0
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:latest'
          format: 'sarif'
          output: 'trivy-image-latest-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy to Scan Docker Image (versioned)
        uses: aquasecurity/trivy-action@0.15.0
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:${{ needs.build.outputs.version }}'
          format: 'sarif'
          output: 'trivy-image-versioned-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy Scan Results (latest)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-image-latest-results.sarif'

      - name: Upload Trivy Scan Results (versioned)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-image-versioned-results.sarif'

  push_image:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: security_scan

    steps:
      - name: Download Docker Image Artifact (latest)
        uses: actions/download-artifact@v4
        with:
          name: docker-image-latest
          path: .

      - name: Download Docker Image Artifact (versioned)
        uses: actions/download-artifact@v4
        with:
          name: docker-image-versioned
          path: .

      - name: Load Docker Images
        run: |
          docker load -i image-latest.tar
          docker load -i image-${{ needs.build.outputs.version }}.tar

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:${{ needs.build.outputs.version }}
          echo "Pushed Docker Images: latest and ${{ needs.build.outputs.version }}"
