name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # ทำงานเมื่อ Push ไปที่ branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Auto Version
        id: version
        run: |
          VERSION="v${{ github.run_number }}.0"  # ใช้ run_number ที่เพิ่มขึ้นทุกครั้ง
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Next version: $VERSION"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:${{ env.VERSION }}
