name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # ทำงานเมื่อ Push ไปที่ branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Auto Version
        id: version
        run: |
          VERSION="v${{ github.run_number }}.0"  # ใช้ run_number ที่เพิ่มขึ้นทุกครั้ง
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Next version: $VERSION"

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:${{ env.VERSION }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:latest

      - name: Save Docker Image as Artifact
        uses: actions/upload-artifact@v4  # เปลี่ยนจาก v3 เป็น v4
        with:
            name: docker-image
            path: /tmp/docker-image.tar

  push:
    runs-on: ubuntu-latest
    needs: build  # รอให้ job "build" เสร็จก่อน
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4  # เปลี่ยนจาก v3 เป็น v4
        with:
              name: docker-image
              path: /tmp

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Load and Push Docker Image
        run: |
          docker load -i /tmp/docker-image.tar
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:${{ env.VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-my-app:latest
