name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install SonarScanner
        run: |
          curl -LsS https://downloads.sonarsource.com/sonarqube/sonar-scanner-cli.zip -o sonar-scanner.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-* sonar-scanner
          echo "$PWD/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Run SonarCloud Scan
        run: |
          sonar-scanner \
            -Dsonar.organization=kalangun \
            -Dsonar.projectKey=kalangun_test-my-app \
            -Dsonar.sources=. \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
