name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # จำเป็นสำหรับ SonarCloud เพื่อวิเคราะห์โค้ดได้ถูกต้อง

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter (ESLint)
        run: npm run lint || true  # ป้องกัน CI ล้มเหลวหากมี warning

      - name: Run SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ใช้เพื่อดึงข้อมูล PR
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token สำหรับเชื่อมต่อ SonarCloud
        run: |
          npx sonarqube-scanner \
            -Dsonar.projectKey=kalangun69300_test-my-app \
            -Dsonar.organization=kalangun69300 \
            -Dsonar.sources=src \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.token="${{ secrets.SONAR_TOKEN }}"

