name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SonarScanner
        run: |
          curl -LsS https://downloads.sonarsource.com/sonarqube/sonar-scanner-cli.zip -o sonar-scanner.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-* sonar-scanner
          echo "${GITHUB_WORKSPACE}/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Verify SonarScanner
        run: sonar-scanner -h

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my-project \
            -Dsonar.sources=. \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.login=${SONAR_TOKEN}
